/** @type {import('next').NextConfig} */
const nextConfig = {
  // Keep `next dev` isolated from production chunks generated by `next build`.
  distDir:
    process.env.NEXT_DIST_DIR ??
    (process.env.NODE_ENV === "development" ? ".next-dev" : ".next"),
  reactStrictMode: true
};

export default nextConfig;
